import typing


class Solution:
    def solve(self, spec_path: str = None) -> dict:
        code = (
            "import torch\n"
            "import triton\n"
            "import triton.language as tl\n"
            "\n"
            "@triton.jit\n"
            "def gelu(x):\n"
            "    return x * 0.5 * (1.0 + tl.extra.cuda.libdevice.erf(x * 0.7071067811865476))\n"
            "\n"
            "@triton.autotune(\n"
            "    configs=[\n"
            "        triton.Config({'BLOCK_M': 128, 'BLOCK_N': 128, 'BLOCK_K': 32}, num_warps=8, num_stages=3),\n"
            "        triton.Config({'BLOCK_M': 64, 'BLOCK_N': 128, 'BLOCK_K': 32}, num_warps=4, num_stages=3),\n"
            "        triton.Config({'BLOCK_M': 128, 'BLOCK_N': 64, 'BLOCK_K': 32}, num_warps=4, num_stages=3),\n"
            "        triton.Config({'BLOCK_M': 64, 'BLOCK_N': 64, 'BLOCK_K': 32}, num_warps=4, num_stages=2),\n"
            "        triton.Config({'BLOCK_M': 256, 'BLOCK_N': 64, 'BLOCK_K': 32}, num_warps=8, num_stages=3),\n"
            "        triton.Config({'BLOCK_M': 64, 'BLOCK_N': 256, 'BLOCK_K': 32}, num_warps=8, num_stages=3),\n"
            "        triton.Config({'BLOCK_M': 128, 'BLOCK_N': 128, 'BLOCK_K': 64}, num_warps=8, num_stages=4),\n"
            "    ],\n"
            "    key=['M', 'N', 'K'],\n"
            ")\n"
            "@triton.jit\n"
            "def _matmul_kernel(\n"
            "    A_ptr, B_ptr, C_ptr,\n"
            "    M, N, K: tl.constexpr,\n"
            "    stride_am, stride_ak,\n"
            "    stride_bk, stride_bn,\n"
            "    stride_cm, stride_cn,\n"
            "    OUT_DTYPE: tl.constexpr,\n"
            "    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr,\n"
            "):\n"
            "    pid_m = tl.program_id(0)\n"
            "    pid_n = tl.program_id(1)\n"
            "\n"
            "    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)\n"
            "    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)\n"
            "    offs_k = tl.arange(0, BLOCK_K)\n"
            "\n"
            "    a_ptrs = A_ptr + (offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak)\n"
            "    b_ptrs = B_ptr + (offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn)\n"
            "\n"
            "    acc = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.float32)\n"
            "\n"
            "    for k in range(0, K, BLOCK_K):\n"
            "        a_mask = (offs_m[:, None] < M) & (offs_k[None, :] + k < K)\n"
            "        b_mask = (offs_k[:, None] + k < K) & (offs_n[None, :] < N)\n"
            "        a = tl.load(a_ptrs, mask=a_mask, other=0.0)\n"
            "        b = tl.load(b_ptrs, mask=b_mask, other=0.0)\n"
            "        acc += tl.dot(a, b)\n"
            "        a_ptrs += BLOCK_K * stride_ak\n"
            "        b_ptrs += BLOCK_K * stride_bk\n"
            "\n"
            "    acc = gelu(acc)\n"
            "\n"
            "    if OUT_DTYPE == 0:\n"
            "        out = acc\n"
            "    elif OUT_DTYPE == 1:\n"
            "        out = tl.cast(acc, tl.float16)\n"
            "    elif OUT_DTYPE == 2:\n"
            "        out = tl.cast(acc, tl.bfloat16)\n"
            "    else:\n"
            "        out = acc\n"
            "\n"
            "    c_mask = (offs_m[:, None] < M) & (offs_n[None, :] < N)\n"
            "    c_ptrs = C_ptr + (offs_m[:, None] * stride_cm + offs_n[None, :] * stride_cn)\n"
            "    tl.store(c_ptrs, out, mask=c_mask)\n"
            "\n"
            "def matmul(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:\n"
            "    \"\"\"Matrix multiplication with GELU activation using a Triton kernel.\"\"\"\n"
            "    if a.dim() != 2 or b.dim() != 2:\n"
            "        raise ValueError(\"Inputs must be 2D tensors\")\n"
            "    if a.shape[1] != b.shape[0]:\n"
            "        raise ValueError(\"Inner dimensions must match for matmul\")\n"
            "\n"
            "    if not a.is_cuda or not b.is_cuda:\n"
            "        return torch.nn.functional.gelu(a @ b)\n"
            "\n"
            "    M, K = a.shape\n"
            "    Kb, N = b.shape\n"
            "    if Kb != K:\n"
            "        raise ValueError(\"Inner dimensions must match for matmul\")\n"
            "\n"
            "    if a.dtype != b.dtype:\n"
            "        raise TypeError(\"Input tensors must have the same dtype\")\n"
            "\n"
            "    if a.dtype == torch.float16:\n"
            "        out_dtype_id = 1\n"
            "    elif a.dtype == torch.bfloat16:\n"
            "        out_dtype_id = 2\n"
            "    elif a.dtype == torch.float32:\n"
            "        out_dtype_id = 0\n"
            "    else:\n"
            "        return torch.nn.functional.gelu(a @ b)\n"
            "\n"
            "    if not a.is_contiguous():\n"
            "        a = a.contiguous()\n"
            "    if not b.is_contiguous():\n"
            "        b = b.contiguous()\n"
            "\n"
            "    c = torch.empty((M, N), device=a.device, dtype=a.dtype)\n"
            "\n"
            "    stride_am, stride_ak = a.stride()\n"
            "    stride_bk, stride_bn = b.stride()\n"
            "    stride_cm, stride_cn = c.stride()\n"
            "\n"
            "    grid = lambda META: (\n"
            "        triton.cdiv(M, META['BLOCK_M']),\n"
            "        triton.cdiv(N, META['BLOCK_N']),\n"
            "    )\n"
            "\n"
            "    _matmul_kernel[grid](\n"
            "        a, b, c,\n"
            "        M, N, K,\n"
            "        stride_am, stride_ak,\n"
            "        stride_bk, stride_bn,\n"
            "        stride_cm, stride_cn,\n"
            "        OUT_DTYPE=out_dtype_id,\n"
            "    )\n"
            "\n"
            "    return c\n"
        )
        return {"code": code}
